name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tdeboissiere/python-format-action@master
      - uses: stefanzweifel/git-auto-commit-action@v6
